version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2182:2181"
  kafka:
    image: wurstmeister/kafka
#    build:
#      context: kafka
#      dockerfile: Dockerfile
    links:
      - zookeeper:zk
    ports:
      - "9095:9092"
    environment:
#      KAFKA_ADVERTISED_HOST_NAME: $CF_HOST_IP
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_CREATE_TOPICS: "Topic1:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  spring_boot:
    build: .
    depends_on:
      - kafka
      - zookeeper